defaults:
  - _self_
  - network
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled 

camera_address: '172.24.71.211'
robot_cam_serial_numbers:
  - '147322072736'
  - '147322072546'
  - '028522071213'

cam_configs:
  width: 640
  height: 480
  fps: 30
  processing_preset: 1 # High accuracy mode
  rotation_angle: 0

oculus_cam: 0 # First camera
stream_oculus: False

hydra:  
  output_subdir: null  
  run:  
    dir: .