defaults:
  - _self_
  - camera
  - network
  - robot: xarm_stick_reskin
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled 

# storage_path: /home/raunaq/code/Open-Teach/extracted_data/0607_rand_test

# task_name: test
# storage_path: extracted_data/${oc.env:DATE}_${task_name}

storage_path: extracted_data/0612_picknplace_cups

demo_num: 0
sim_env: false
use_sensor: true
host: ${host_address}

hydra:  
  output_subdir: null  
  run:  
    dir: .
