defaults:
  - _self_
  - camera
  - network
  - robot: xarm_stick_reskin
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled 

storage_path: /mnt/robotlab/raunaq/data/crossmodal/venky/0627_cardswipe
demo_num: 0
sim_env: false
use_sensor: true
is_xela: false
host: ${host_address}



hydra:  
  output_subdir: null  
  run:  
    dir: .
