defaults:
  - _self_
  - camera
  - network
  - robot: xarm_stick_reskin
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled 

storage_path: extracted_data/0607_rand
demo_num: 0
sim_env: false
use_sensor: true
host: ${host_address}


hydra:  
  output_subdir: null  
  run:  
    dir: .