defaults:
  - _self_
  - camera
  - network
  - robot: xarm_stick
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled 

storage_path: extracted_data/xarm_test
demo_num: 0
sim_env: false
use_sensor: false
host: ${host_address}



hydra:  
  output_subdir: null  
  run:  
    dir: .
