defaults:
  - _self_
  - camera
  - network
  - robot: onrobot_kinova
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled 

storage_path: extracted_data/cup_ball
demo_num: 271
sim_env: false
use_sensor: false
host: ${host_address}



hydra:  
  output_subdir: null  
  run:  
    dir: .