defaults:
  - _self_
  - network
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled 

stream_configs:
  host: ${sensor_host_address}
  port: ${reskin_publisher_port}

reskin_config:
  port: ${reskin_port}
  num_mags: ${reskin_num_mags}