x_coord: 0.054 # Fixing X for 2D movement
index:
  -
    x_bounds: [0.013538254,0.047969904]
    y_bounds: [-0.1128674,0.1187463]
    z_bounds: [-0.107926,-0.0195138]
    projective_bounds:
      - #Top right
        - 0.0509640553
        - 0.12033194
      - # Top left
        - 0.0226578
        - 0.1288781
      - # Bottom left
        - -0.00323276
        - -0.09688505
      - # Bottom right
        - 0.0226578
        - -0.0986447

      
middle:
  -
    x_bounds: [-0.03163805,-0.01408815]
    y_bounds: [-0.1128674,0.1187463]
    z_bounds: [-0.107926,-0.0195138]
    projective_bounds:
      - #Top right
        - -0.012983562
        - 0.126939528
      - # Top left
        - -0.0327480383
        - 0.129816228
      - # Bottom left
        - -0.02594544
        - -0.09459023
      - # Bottom right
        - -0.0197861617
        - -0.09448207283

ring:
  -
    x_bounds: [-0.0948495,-0.05953815]
    y_bounds: [-0.1128674,0.1187463]
    z_bounds: [-0.107926,-0.0195138]
    projective_bounds:
      - #Top right
        - -0.0682422
        - 0.1288781
      - # Top left
        - -0.0781980383
        - 0.129816228
      - # Bottom left
        - -0.0682422
        - -0.088369
      - # Bottom right
        - -0.0652361617
        - -0.0880757283
thumb_bounds:
  # - # thumb_index
  #   x_bounds: [0.0169, 0.117]
  #   projective_bounds:
  #     - # Top right
  #       - 0.1154
  #       - -0.0051
  #     - # Bottom right
  #       - 0.1321
  #       - -0.0481
  #     - # index_top
  #       - 0.0495
  #       - 0.0106
  #     - # Index bottom
  #       - 0.0413
  #       - -0.1017

  # - # index_middle
  #   x_bounds: [0.054, 0.117]
  #   projective_bounds:
  #     - # index_top
  #       - 0.0495
  #       - 0.0106
  #     - # index_bottom
  #       - 0.0413
  #       - -0.1017
  #     - # middle_top
  #       - 0.0094
  #       - 0.0124
  #     - # middle_bottom
  #       -  0.0079
  #       - -0.0997

  # - # middle_ring
  #   x_bounds: [0.0518, 0.117]
  #   projective_bounds:
  #     - # middle_top:
  #       - 0.0094
  #       - 0.0124
  #     - # middle_bottom
  #       -  0.0079
  #       - -0.0997
  #     - # ring_bottom
  #       - -0.0373
  #       - -0.0961
  #     - # ring_top
  #       - -0.024
  #       - -0.0087
  - # middle_ring
    x_bounds: [-0.1605669,-0.00691154] # Here we're getting the smallest limits
    projective_bounds:
      - # Top right
        - 0.136406
        - 0.036005
      - # Bottom right
        - 0.1866778
        - -0.00709525
      - # ring_bottom
        - -0.130968
        - -0.00709525
      - # ring_top
        - -0.0368922
        - 0.036005